"use client";

import React, { useEffect, useState } from "react";
import GridBox from "./gridbox";

const Grid = () => {
  return (
    <div className="grid grid-cols-[repeat(auto-fit,minmax(100px,1fr))] max-w-screen-lg mx-auto w-full h-full max-w-[1960px] gap-[50px]">
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-900"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-900"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
      <GridBox color="bg-emerald-100"></GridBox>
      <GridBox color="bg-emerald-200"></GridBox>
      <GridBox color="bg-emerald-300"></GridBox>
      <GridBox color="bg-emerald-400"></GridBox>
      <GridBox color="bg-emerald-500"></GridBox>
      <GridBox color="bg-emerald-600"></GridBox>
      <GridBox color="bg-emerald-700"></GridBox>
      <GridBox color="bg-emerald-800"></GridBox>
    </div>
  );
};

export default Grid;
